/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 *
 * @author Rasyid_
 */

public class DataPelanggan extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataPelanggan
     */
    Connection conn = null;
    PreparedStatement pst = null;
    Statement stat;
    ResultSet rs = null;
    int idPelanggan;
    
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    DefaultTableModel tableModel = new DefaultTableModel(
	new Object[][]{},
	new String[]{
		"idPelanggan","Nama","Jenis_kelamin","Agama","Alamat","Phone","Hobi"
	}
    );

    public DataPelanggan() {
        initComponents();
        setLocation(d.width/2 - getWidth()/2, d.height/2 - getHeight()/2);
        jTablePelanggan.setModel(tableModel);
        getDataPelanggan();
    }

    private void getDataPelanggan(){
    //menghapus isi table dataPelanggan
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        try{
            //membuat statemen pemanggilan data pada table tblGaji dari database
            //Statement stat = (Statement) ctrlKoneksi.configDB().createStatement();
            stat = (Statement) ctrlKoneksi.mariaDB().createStatement();
            String sql = "SELECT * FROM datapelanggan ORDER BY idpelanggan DESC";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                Object[] obj = new Object[7];
                obj[0] = rs.getString("idPelanggan");
                obj[1] = rs.getString("Nama");
                obj[2] = rs.getString("Jenis_kelamin");
                obj[3] = rs.getString("Agama");
                obj[4] = rs.getString("Alamat");
                obj[5] = rs.getString("Phone");
                obj[6] = rs.getString("Hobi");
                tableModel.addRow(obj);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonL = new javax.swing.JRadioButton();
        jRadioButtonP = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelAlamat = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextAreaAlamat = new javax.swing.JTextField();
        jLabelTelepon = new javax.swing.JLabel();
        jLabelJK = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabelHobi = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButtonSimpan = new javax.swing.JButton();
        jButtonUbah = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePelanggan = new javax.swing.JTable();
        jLabelAgama = new javax.swing.JLabel();
        jComboBoxAgama = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Master Data Pelanggan");

        buttonGroup1.add(jRadioButtonL);
        jRadioButtonL.setText("Laki-Laki");
        jRadioButtonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonP);
        jRadioButtonP.setText("Perempuan");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("DATA PELANGGAN");

        jLabelNama.setText("Nama");

        jLabelAlamat.setText("Alamat");

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jTextAreaAlamat.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextAreaAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAreaAlamatActionPerformed(evt);
            }
        });

        jLabelTelepon.setText("No. Telepon");

        jLabelJK.setText("Jenis Kelamin");

        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });

        jLabelHobi.setText("Hobi");

        jCheckBox1.setText("Olahraga");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Musik");

        jCheckBox3.setText("Membaca");

        jCheckBox4.setText("Melukis");

        jButtonSimpan.setText("SIMPAN");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonUbah.setText("UBAH");
        jButtonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUbahActionPerformed(evt);
            }
        });

        jButtonHapus.setText("HAPUS");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonKeluar.setText("KELUAR");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jTablePelanggan.setBackground(new java.awt.Color(0, 0, 0));
        jTablePelanggan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTablePelanggan.setForeground(new java.awt.Color(255, 255, 255));
        jTablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "idPelanggan", "Nama", "Jenis_kelamin", "Agama", "Alamat", "Phone", "Hobi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePelanggan);

        jLabelAgama.setText("Agama");

        jComboBoxAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Buddha", "Kristen", "Coki" }));
        jComboBoxAgama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAgamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAlamat)
                            .addComponent(jLabelNama)
                            .addComponent(jLabelHobi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox2)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox3)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextAreaAlamat)
                                .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSimpan)
                                .addGap(22, 22, 22)
                                .addComponent(jButtonUbah)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHapus)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJK)
                            .addComponent(jLabelTelepon)
                            .addComponent(jLabelAgama))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonKeluar)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonL)
                                        .addComponent(jRadioButtonP))
                                    .addGap(139, 139, 139))
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTelepon)
                                .addGap(20, 20, 20)
                                .addComponent(jLabelJK)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelAgama)
                                    .addComponent(jComboBoxAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(jRadioButtonL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonP)))
                        .addGap(109, 109, 109)
                        .addComponent(jButtonKeluar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNama)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelAlamat)
                        .addGap(131, 131, 131)
                        .addComponent(jLabelHobi))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jTextAreaAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSimpan)
                            .addComponent(jButtonUbah)
                            .addComponent(jButtonHapus))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        String jk, Hobi;
        if(jRadioButtonL.isSelected()){ jk = "Laki-Laki"; } else { jk = "Perempuan"; }
        Hobi ="";
        if(jCheckBox1.isSelected()){ Hobi += jCheckBox1.getText() + ","; }
        if(jCheckBox2.isSelected()){ Hobi += jCheckBox2.getText() + ","; }
        if(jCheckBox3.isSelected()){ Hobi += jCheckBox3.getText() + ","; }
        if(jCheckBox4.isSelected()){ Hobi += jCheckBox4.getText() + ","; }
        try{
            conn = ctrlKoneksi.mariaDB();
            String sql = "INSERT INTO datapelanggan (Nama,Jenis_kelamin,Agama,Alamat,Phone,Hobi) VALUES ("
            + "'"+jTextFieldNama.getText()+"',"
            + "'"+jk+"',"
            + "'"+jComboBoxAgama.getSelectedItem()+"',"
            + "'"+jTextAreaAlamat.getText()+"',"
            + "'"+jTextFieldPhone.getText()+"',"
            + "'"+Hobi+"'"
            + ")";
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            getDataPelanggan();
        } catch(Exception e){
            jTextPane1.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jTextAreaAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAreaAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaAlamatActionPerformed

    private void jTablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePelangganMouseClicked
        // TODO add your handling code here:
        String Hobi;
        if(evt.getClickCount()==1){
            int row = jTablePelanggan.getSelectedRow();
            idPelanggan = Integer.parseInt(tableModel.getValueAt(row, 0).toString());
            jTextFieldNama.setText(tableModel.getValueAt(row, 1).toString());
            if(tableModel.getValueAt(row, 2).toString().equals("Laki-Laki")){
                jRadioButtonL.setSelected(true);
            }else{
                jRadioButtonP.setSelected(true);
            }
            jComboBoxAgama.setSelectedItem(tableModel.getValueAt(row, 3).toString());
            jTextAreaAlamat.setText(tableModel.getValueAt(row, 4).toString());
            jTextFieldPhone.setText((tableModel).getValueAt(row, 5).toString());
            Hobi = tableModel.getValueAt(row, 6).toString();
            if(Hobi.equals("Olahraga,")) {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(false);   
            } else if (Hobi.equals("Musik,")) {
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(false);
            } else if (Hobi.equals("Membaca,")) {
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(true);
                jCheckBox4.setSelected(false);
            } else if (Hobi.equals("Melukis,")) {
                jCheckBox1.setSelected(false);
                jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(true);
            }
    }

    }//GEN-LAST:event_jTablePelangganMouseClicked

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try{
            conn = ctrlKoneksi.mariaDB();
            String sql = "DELETE FROM datapelanggan WHERE idPelanggan='"+idPelanggan+"'";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            getDataPelanggan();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        getDataPelanggan();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUbahActionPerformed
        // TODO add your handling code here:
        String jk, Hobi;
        if(jRadioButtonL.isSelected()){ jk = "Laki-Laki"; } else { jk = "Perempuan"; } Hobi ="";
        if(jCheckBox1.isSelected()){ Hobi += jCheckBox1.getText() + ","; }
        if(jCheckBox2.isSelected()){ Hobi += jCheckBox2.getText() + ","; }
        if(jCheckBox3.isSelected()){ Hobi += jCheckBox3.getText() + ","; }
        if(jCheckBox4.isSelected()){ Hobi += jCheckBox4.getText() + ","; }
        try{
            conn = ctrlKoneksi.mariaDB();
            String sql = "UPDATE datapelanggan SET "
            + " Nama='"+jTextFieldNama.getText()+"',"
            + " Jenis_kelamin='"+jk+"',"
            + " Agama='"+jComboBoxAgama.getSelectedItem()+"',"
            + " Alamat='"+jTextAreaAlamat.getText()+"',"
            + " Phone='"+jTextFieldPhone.getText()+"',"
            + " Hobi='"+Hobi+"'"
            + " WHERE idPelanggan='"+idPelanggan+"' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Ubah");
            getDataPelanggan(); 
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        //getDataPelanggan();
    }//GEN-LAST:event_jButtonUbahActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jComboBoxAgamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAgamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAgamaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUbah;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBoxAgama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgama;
    private javax.swing.JLabel jLabelAlamat;
    private javax.swing.JLabel jLabelHobi;
    private javax.swing.JLabel jLabelJK;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelTelepon;
    private javax.swing.JRadioButton jRadioButtonL;
    private javax.swing.JRadioButton jRadioButtonP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePelanggan;
    private javax.swing.JTextField jTextAreaAlamat;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables

    private static class jTextPane1 {

        private static void showMessageDialog(Object object, String data_Berhasil_Disimpan) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public jTextPane1() {
        }
    }

//    private static class ResultSet {
//
//        public ResultSet() {
//        }
//
//        private boolean next() {
//            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//        }
//
//        private Object getString(String nama) {
//            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//        }
//    }
}
