/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;

/**
 *
 * @author Rasyid_
 */

public class DataProduk extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataProduk
     */
    Connection conn = null;
    PreparedStatement pst = null;
    Statement stat;
    ResultSet rs = null;
    int idProduk;
    
    Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
    DefaultTableModel tableModel = new DefaultTableModel(
	new Object[][]{},
	new String[]{
		"idProduk","NamaProduk","HargaProduk","Stokbarang"
	}
    );
    
    public DataProduk() {
        initComponents();
        setLocation(d.width/2 - getWidth()/2, d.height/2 - getHeight()/2);
        jTableListProduk.setModel(tableModel);
        getDataProduk();
    }
    
    private void getDataProduk(){
    //menghapus isi table dataPelanggan
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();
        try{
            //membuat statemen pemanggilan data pada table tblGaji dari database
            //Statement stat = (Statement) ctrlKoneksi.configDB().createStatement();
            stat = (Statement) ctrlKoneksi.mariaDB().createStatement();
            String sql = "SELECT * FROM dataproduk ORDER BY idProduk DESC";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                Object[] obj = new Object[4];
                obj[0] = rs.getString("idProduk");
                obj[1] = rs.getString("NamaProduk");
                obj[2] = rs.getString("HargaProduk");
                obj[3] = rs.getString("StokBarang");
                tableModel.addRow(obj);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTambahProduk = new javax.swing.JLabel();
        jLabelListProduk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListProduk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNamaProduk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHargaProduk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonTambah = new javax.swing.JButton();
        jButtonSimpan = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jButtonKeluar = new javax.swing.JButton();
        jTextFieldStok = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Master Data Produk");
        setMinimumSize(new java.awt.Dimension(74, 34));
        setPreferredSize(new java.awt.Dimension(718, 489));

        jLabelTambahProduk.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelTambahProduk.setText("TAMBAH PRODUK");

        jLabelListProduk.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabelListProduk.setText("LIST PRODUK");

        jLabel2.setText("Nama Produk");

        jTableListProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idProduk", "NamaBarang", "StokBarang", "HargaBarang"
            }
        ));
        jTableListProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListProduk);

        jLabel1.setText("Harga Produk");

        jTextFieldNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaProdukActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("RP");

        jTextFieldHargaProduk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldHargaProduk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldHargaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHargaProdukActionPerformed(evt);
            }
        });

        jLabel3.setText("Stok Barang");

        jButtonTambah.setText("Tambah");
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonSimpan.setText("Update");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTambahProduk)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelListProduk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonKeluar)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldHargaProduk))
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonTambah)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSimpan)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(jButtonHapus))
                            .addComponent(jTextFieldStok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTambahProduk)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldHargaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonTambah)
                            .addComponent(jButtonSimpan)
                            .addComponent(jButtonHapus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKeluar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelListProduk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaProdukActionPerformed

    private void jTextFieldHargaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHargaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHargaProdukActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        // TODO add your handling code here:
        int Harga, Stok;
        try{
            conn = ctrlKoneksi.mariaDB();
            String sql = "INSERT INTO dataproduk (NamaProduk,HargaProduk,StokBarang) VALUES ("
            + "'"+jTextFieldNamaProduk.getText()+"',"
            + "'"+jTextFieldHargaProduk.getText()+"',"
            + "'"+jTextFieldStok.getText()+"'"
            + ");";
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Produk Berhasil Ditambahkan!");
            getDataProduk();
        } catch(Exception e){
            jTextPane1.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        // TODO add your handling code here:
        try{
            conn = ctrlKoneksi.mariaDB();
            String sql = "UPDATE dataproduk SET "
            + " NamaProduk='"+jTextFieldNamaProduk.getText()+"',"
            + " HargaProduk='"+jTextFieldHargaProduk.getText()+"',"
            + " StokBarang='"+jTextFieldStok.getText()+"'"
            + " WHERE idProduk='"+idProduk+"';";
            pst = conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Update Data Produk Berhasil!");
            getDataProduk(); 
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        try{
            conn = ctrlKoneksi.mariaDB();
            String sql = "DELETE FROM dataproduk WHERE idProduk='"+idProduk+"';";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Produk Berhasil Dihapus");
            getDataProduk();
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        getDataProduk();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jTableListProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListProdukMouseClicked
        // TODO add your handling code here:
        int Stok;
        if(evt.getClickCount()==1){
            int row = jTableListProduk.getSelectedRow();
            idProduk = Integer.parseInt(tableModel.getValueAt(row, 0).toString());
            jTextFieldNamaProduk.setText(tableModel.getValueAt(row, 1).toString());
            jTextFieldHargaProduk.setText(tableModel.getValueAt(row, 2).toString());
            jTextFieldStok.setText(tableModel.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_jTableListProdukMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelListProduk;
    private javax.swing.JLabel jLabelTambahProduk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListProduk;
    private javax.swing.JTextField jTextFieldHargaProduk;
    private javax.swing.JTextField jTextFieldNamaProduk;
    private javax.swing.JTextField jTextFieldStok;
    // End of variables declaration//GEN-END:variables
    
    private static class jTextPane1 {

        private static void showMessageDialog(Object object, String data_Berhasil_Disimpan) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public jTextPane1() {
        }
    }
}

